# Funciones

Ya hemos visto algunas funciones pre-definidas, pero eso nos deja casi en el nivel de una calculadora. 

En este notebook veremos cómo definir funciones propias que podamos aplicar a nuestros objetos. Con esto tendremos todo lo necesario para "hablar Julia". Es decir, tendremos las oraciones completas, con sujeto (los objetos) y predicado (las funciones). 

## Forma directa de definir una función. 

Ya vimos también que una forma directa de definir una función, es usando el signo "=":

In [6]:
cuadrado(x) = x^2

cuadrado (generic function with 1 method)

In [7]:
cuadrado(5)

25

In [8]:
saludo(nombre::String) = "Hola $nombre, ¿cómo te va?"

saludo (generic function with 1 method)

In [9]:
saludo("Ata")

"Hola Ata, ¿cómo te va?"

Esta clase de funciones son útiles, pero si por ejemplo queremos hacer la siguiente función: 


\begin{equation}
f(x) = \begin{cases} 
x/2 &\mbox{if } x < 0 \\
x^2 & \mbox{if } x \ge 0 
\end{cases}.
\end{equation}

tendremos problemas para definirla. Para ello necesitamos primero que nada definir el condicional **if**

## Bloques de código

Llamaremos bloques de código, o simplemente bloques, a todos los comandos que para terminarlos se utiliza la palabra **end**. Es decir, típicamente tienen la forma 

    comando algo
        código
    end
    
No veremos todos los tipos de bloques, pero veremos los principales, comenzando por el condicional **if**.

### Condicional if

**Nota:** Este condicional tiene una forma compacta de escribirse, pero no es cómo para leerse, así que omitiré cómo hacerlo. En este curso (y recomendable en su vida), no utilicen la forma compacta de escribir el condicional if. 

Para iniciar el condicional if, se escribe tal cual la palabra **if** en minúsculas. Segudio se tiene que dar la condición, que debe un booleano que si es "true" se aplica la condición, si no, se omite. Después se escriben las instrucciones que se deben seguir y finalmente se termina con un **end**. Por ejemplo: 

In [10]:
if 1 <= 2
    println("hola")
end

hola


Además de incluir una acción en caso de que se cumpla la condición, se puede agregar otra acción en caso de que no se cumpla la condición, esto se hace con "else": 

In [11]:
test = true
if test
    println("hola")
else
    println("adiós")
end

hola


Finalmente, se puede incluir un condicional interno en caso de que no se cumpla el primero o los primeros. Para esto se usa "elseif" seguido de la siguiente condición: 

In [12]:
nombre = "fulanita"
genero = "mujer"
if genero == "mujer"
    println("Buenos días señorita $nombre")
elseif genero == "hombre"
    println("Buenos días señor $nombre")
elseif genero == "gato"
    println("miua miau $nombre")
else
    println("No saludo si no sé que eres")
end

Buenos días señorita fulanita


### Bloques de funciones

Cuando una función es más compleja que una linea de código, conviene definir dónde comienza (con el comando **function**) y dónde termina (**end**). Por ejemplo: 

In [13]:
function saludo(nombre, genero)
    if genero == "mujer"
        println("Buenos días señorita $nombre")
        1
    elseif genero == "hombre"
        println("Buenos días señor $nombre")
        2
        3
    elseif genero == "gato"
        println("miua miau $nombre")
        3
    else
        println("No saludo si no sé que eres")
    end
    1
end 

saludo (generic function with 2 methods)

In [14]:
saludo("Ata")

"Hola Ata, ¿cómo te va?"

In [15]:
saludo("Ata", "hombre")

Buenos días señor Ata


1

In [16]:
saludo("Fulanita", "mujer")

Buenos días señorita Fulanita


1

In [17]:
saludo("Nimbu", "gato")

miua miau Nimbu


1

In [18]:
saludo("Beethoven", "perro")

No saludo si no sé que eres


1

Además, vale la pena definir el comando "return" que lo único que hace es regresar lo que se tenga delante y terminar la función (o bloque de código). 

In [19]:
function f(x)
    if x < 0
        return x/2
        33
    else
        return x^2
    end
end

f (generic function with 1 method)

In [20]:
f(2), f(-1)

(4, -0.5)

In [21]:
begin # este tipo de bloque no requiere nada más que un comando y dónde termina el bloque. 
    x = 2
    return x
    y = x + 3
    return y
end

2

aquí por ejemplo, nunca calcula $y$, porque antes de definirlo se regresa el valor de $x$ y se termina el bloque de código. 

Con esto podemos hacer realmente mucho si somos creativos. Una de las estrategias para ser creativos es usar funciones iterativas implícitas, es decir, que en su misma definición se corren a si mismas. Por ejemplo: 

$x_n = 1/x_{n-1} +1$

In [22]:
function golden(n, i, dorado)
    if i >= n 
        return i, dorado
    end
    dorado = 1 / dorado + 1
    i += 1
    i, dorado = golden(n, i, dorado)
    return i, dorado
end

"""
Esta función calcula el número dorado con iteraciones y tiene como argumento n un natural, que es el número de iteraciones. 
"""
function golden(n) # esta función calcula el número dorado con iteraciones
    i, dorado = golden(n, 0, 1)
    return dorado
end
    

golden

In [23]:
? golden

search: golden



Esta función calcula el número dorado con iteraciones y tiene como argumento n un natural, que es el número de iteraciones. 


In [24]:
"""
suma(n, contador, s) usa iteraciones para sumar los primeros n números. contador y s tienen que ponerse igual a 0. Si s 
comienza en otra cantidad, se sumará esa cantidad al valor final. Si contador comienza en otra cantidad, se sumará hasta 
n - contador
"""
function suma(n, contador, s)
    if contador >= n
        return contador, s
    end
    contador = contador + 1
    s = s + contador
    contador, s = suma(n, contador, s)
end
function suma(n)
    contador, s = suma(n, 0, 0)
    return s
end

suma (generic function with 2 methods)

In [25]:
suma(500), sum(1:500)

(125250, 125250)

Aunque es bastante poderoso esto de las iteraciones implícitas, frecuentemente conviene escribir las iteraciones de una forma más explícita y para eso hay 2 ciclos que usaremos, for y while. 

### Ciclos for

Los cilos for ya los hemos visto en la notación compacta de arreglos y matrices. Ahora los usaremos para indicar que algo se debe repetir para un conjunto de valores. En general se sigue la estructura

for variable $\in$ arreglo

        proceso
        
end

por ejemplo: 

In [26]:
for x ∈ [1,3,5,[1 2;3 4],"hola "]
    println("el cuadrado de x es $(x^2)")
end

el cuadrado de x es 1
el cuadrado de x es 9
el cuadrado de x es 25
el cuadrado de x es [7 10; 15 22]
el cuadrado de x es hola hola 


Es muy común usar en el arreglo un rango: 

In [27]:
for i ∈ [i^2 for i ∈ 1:10]
    println("i cuadrada es $(i^2)")
end

i cuadrada es 1
i cuadrada es 16
i cuadrada es 81
i cuadrada es 256
i cuadrada es 625
i cuadrada es 1296
i cuadrada es 2401
i cuadrada es 4096
i cuadrada es 6561
i cuadrada es 10000


In [28]:
a = [1,3,5,[1 2;3 4],"hola "]
for i ∈ 1:length(a)
    println(a[i]^2)
end

1
9
25
[7 10; 15 22]
hola hola 


Esto hará que tiendan a escribir siempre for i in rango. No se acostumbren demasiado. Con la notación compacta de arreglos pueden hacer mejores códigos si en vez de recorrer la variable sobre un rango, la recorren sobre los elementos de un arreglo.

Por ejemplo, es mejor:

In [29]:
a = [[1,2], [2,3], [3,4]]
for x ∈ a
    println(x)
end

[1, 2]
[2, 3]
[3, 4]


que: 

In [30]:
a = [[1,2], [2,3], [3,4]]
for i ∈ 1:3
    println(a[i])
end

[1, 2]
[2, 3]
[3, 4]


El resultado es lo mismo (ambos están bien), pero en el primer caso utilizamos directamente el arreglo, lo que hace más legible el código y un código más legible frecuentemente es más rápido y tiene menos errores. 

Con los ciclos conviene aprender 2 comandos útiles. **continue** y **break**. 

Típicamente estos se usan junto con el condicional if y sirven para **pasar directamente al siguiente paso del ciclo** y para **terminar anticipadamente el ciclo** respectivamente. 

In [31]:
for j in 1:2
    for i ∈ 1:10000
        if i == 3  || i> 10
            continue
        end
        println(i)
        if i == 4
            break
        end
    end
    println(j, "hola")
end

1
2
4
1hola
1
2
4
2hola


Estos dos comandos son súmamente útiles para eficientar los códigos, ayudan a evitar cálculos inútiles que quitan tiempo de cómputo. 

### Ciclo while. 

El ciclo while (mientras), sirve para pedir a la computadora que realice una (o varias) acción(es) mientras se cumpla una determinada condición, es decir, mientras una determinada función booleana arroje true. Es un tipo de ciclo "peligroso", porque puede durar eternamente. Por ejemplo

while true

end

es un ciclo que nunca termina. Los ciclos que nunca terminan se pueden a veces detener con el símbolo de "stop" del notebook, pero a veces eso falla y se tiene que reiniciar el kernel (y se pierde todo lo que se haya hecho). Por eso vale la pena correr los ciclos while con un contador como "salida de emergencia": 

In [32]:
contador = 0
while true && contador <1000
    contador += 1
end

# o equivalentemente
contador = 0
while true 
    contador += 1
    if contador>1000
        break
    end 
end

Es decir, agreguen al, menos mientras prueban sus códigos, a todos los ciclos while una condición similar con su respectivo contador. 

Aclarado esto, demos un ejemplo de cómo usar el ciclo while. 

In [33]:
contador = 0
suma2 = 0
while suma2<10_000_500 && contador <1e8
    contador += 1
    suma2 += contador
end
suma2, contador  #calcula la suma de los primeros n números de tal forma que se detiene cuando la suma sobrepasa 99. 
#contador nos dice hasta qué número se sumó

(10001628, 4472)

Ahora sí, combinando los ciclos for y while y el condicional if dentro de una función uno puede hacer toda clase de funciones increíbles. Especialmente si uno agrega sus propios objetos. 

**Nota:** en general una función no debe superar las 50 lineas de código. Hay excepciones, pero lo mejor es tratar de tener funciones muy cortas. Si una función es compleja, conviene separarla en pequeñas funciones más simples (legibles). Entre más pequeñas son las funciones, mejor están escritas. 

**Ejemplo "complicado":**

In [34]:
using LinearAlgebra

In [35]:
mutable struct Persona            # Objeto persona, contiene
    estado_de_salud::Symbol       # un estao de salud que puede ser: :suceptible, :infectado, :enfermo, :muerto o :recuperado. 
    edad::Int                     # la edad de la persona
    tiempo_salud::Real            # el tiempo que lleva la persona en ese estado de salud en días. 
    posicion::Array{Float64,1}    # Un vector de posición de la persona. 
    velocidad::Array{Float64,1}   # un vector de la velocidad de la persona.
end 

In [36]:
"""
Hace una simulació  para saber con probabilidad p_contagiar, si una dos personas se contagian, considerando
un radio de contagio rango_de_contagio. Actualiza la característica del estado_de_salud de los involucrados y también 
el tiempo_salud si alguno se contagia. 
"""
function contagiar!(p1::Persona,p2::Persona; rango_de_contagio = 1, p_contagiar = 0.5) 
    if norm(p1.posicion-p2.posicion) < rango_de_contagio   # si las personas están en el rango de contagio
        if (p1.estado_de_salud == :suceptible && p2.estado_de_salud ∈ [:infectado, :enfermo])  # si uno es suceptible y el otro enfermo o infectado
            test = rand()
            if test<p_contagiar  # el suceptible se enferma con probabilidad de contaciar p_contagiar
                p1.estado_de_salud = :infectado
                p1.tiempo_salud = 0   #el tiempo del estado de salud se actualiza a 0. 
                return true
            end
        elseif (p2.estado_de_salud == :suceptible && p1.estado_de_salud ∈ [:infectado, :enfermo]) #esto es lo mismo que arriba, pero intercambiando quién es suceptible con el infectado. 
            test = rand()
            if test<p_contagiar
                p2.estado_de_salud = :infectado
                p2.tiempo_salud = 0
                return true
            end
        end
    end
    return false  #si no hay contagio regresa false
end    

"""
Actualiza la posición de un conjunto de personas un tiempo delta t
"""
function mover!(p::Persona...; δt = 0.01)
    for ps in p  
        ps.posicion .+= ps.velocidad*δt  # para cada persona de la tupla actualiza la posición. 
    end
end

"""
Actualiza la velocidad de un conjunto de personas cambiando aleatoriamente la dirección de movimiento 
"""
function cambiar_velocidad!(p::Persona...)
    for ps ∈ p # para cada persona en la tupla
        test = rand()
        if test<0.2
            θ = rand(0:0.001:2π) # se obtiene un valor aleatorio entre 0 y 2pi para el ángulo. 
            v₀ = [cos(θ), sin(θ)]*0.1 # se obtiene un vector de velocidad pequeño y aleatorio con distribución normal en el círculo
            ps.velocidad .+= v₀  # se actualiza la velocidad de la persona cambiandola "ligeramente" de forma aleatoria.
        end
    end
end

"""
Evoluciona un paso de tiempo delta t a un conjunto de personas. 
"""
function evolucionar!(p::Persona...; p_enfermar = 0.1, p_muerte = 0.1, δt = 0.01)
    for ps ∈ p  # para cada persona en la tupla
        if ps.estado_de_salud == :infectado # si la persona está infectada
            test = rand()
            if test < p_enfermar #con probabilidad p_enfermar 
                ps.estado_de_salud = :enfermo # se enferma
                ps.tiempo_salud = 0 # y se actualiza su tiempo de salud. 
                continue # si ya se actualizó la situación de esta persona, se pasa a la siguiente. 
            end
        end
        if ps.estado_de_salud ∈ [:infectado, :enfermo] # si es contagioso
            test = rand() 
            if test < p_muerte # con probabilidad p_muerte
                ps.estado_de_salud = :muerto #se muere
                ps.tiempo_salud = 0 #y se actualiza el tiempo en ese estado. 
                continue # si ya se actualizó la situación de esta persona, se pasa a la siguiente. 
            else
                if ps.tiempo_salud >= 15  #después de 15 días de estar infectado o enfermo (o exclusivo)
                    ps.estado_de_salud = :recuperado # pasa a estar recuperado
                    ps.tiempo_salud = 0 # y se actualiza el estado de salud.
                    continue # si ya se actualizó la situación de esta persona, se pasa a la siguiente. 
                end
            end
        end
        ps.tiempo_salud += δt # se actualiza el tiempo en un estado de salud si no cambió el estado de salud de la persona. 
    end
    return p
end         

evolucionar!

In [37]:
"""
regresa true si hay alguna persona que sea contagiosa. 
"""
function estado_final(p::Persona...) 
    test = false # se inicializa en falso el booleano que se regresará
    for persona ∈ p  
        if persona.estado_de_salud ∉ [:suceptible, :recuperado, :muerto] # si  hay alguna persona que sea contagiosa
            test = true  #se cambia el booleano a false y se termina el ciclo for. 
            break
        end
    end
    return test 
end

"""
Cuenta cuantos casos hay de cada estado de salud en una tupla de personas. 
"""
function contar_casos(p::Persona...)
    Suceptibles, Infectados, Enfermos, Muertos, Recuperados = 0,0,0,0,0 #se inicializa el número de cada estado de salud en 0. 
    for ps ∈ p # para cada persona en la tupla
        if ps.estado_de_salud == :suceptible  
            Suceptibles += 1   # se cuenta el número de suceptibles
        elseif ps.estado_de_salud == :infectado
            Infectados += 1 # se cuenta el número de infectados
        elseif ps.estado_de_salud == :enfermo
            Enfermos += 1   # se cuenta el número de enfermos
        elseif ps.estado_de_salud == :muerto
            Muertos += 1   # se cuenta el número de muertos
        elseif ps.estado_de_salud == :recuperado
            Recuperados += 1   # se cuenta el número de recuperados
        end
    end
    return Suceptibles, Infectados, Enfermos, Muertos, Recuperados
end

contar_casos

In [38]:
"""
Actualiza las características de una tupla de personas hasta que no haya ninguna persona que sea contagiosa e imprime
en cada paso de tiempo el número de Siceptibles, Infectados, Enfermos, Muertos y Recuperados. 
"""
function simular_contagios(p::Persona...; p_enfermar = 0.1, p_muerte = 0.1, 
                           p_contagiar = 0.5, δt = 0.1, rango_de_contagio = .01)

    n = length(p)  # Obtiene el número de personas
    test = true    # cuando no quede ningún contagioso, test será false y la simulación se termina. 
    contador = 0    
    while test
        for i ∈ 1:n-1       # Para cada par de personas en la tupla 
            for j in i+1:n  # se simula un posible contagio.  
                contagiar!(p[i], p[j], rango_de_contagio = rango_de_contagio, p_contagiar = p_contagiar)
            end
        end
        mover!(p..., δt = δt) # se mueven las personas un tiempo δt. 
        cambiar_velocidad!(p...) # se cambia la velocidad de las personas. 
        evolucionar!(p..., p_enfermar = p_enfermar, p_muerte = p_muerte, δt = δt) # se evolucionan los estados y tiempos de salud. 
        Suceptibles, Infectados, Enfermos, Muertos, Recuperados = contar_casos(p...) # se cuenta el número de casos de cada estao de salud. 
        test = estado_final(p...)  # se revisa si quedan personas contagiosas. 
        contador += 1 # se actualiza un contador que detenga el programa en caso de emergencia. 
        println("Suceptibles = $Suceptibles, Infectados = $Infectados, Enfermos  = $Enfermos, 
            Muertos  = $Muertos, Recuperados  = $Recuperados") #imprime el número de casos de cada tipo. 
        if contador > 100000 
            break # en caso de emergencia se detiene el programa. 
        end
    end  
end

simular_contagios

In [39]:
function push(elemento, tupla...)  # hago mi función push para tuplas. 
    if length(tupla)> 0
        return tupla..., elemento  # cuando la tupla es una tupla verdaderoa
    else
        return (elemento,) #cuando la tupla es un elemento vacío, se genera una tupla con un solo elemento. 
    end
end

push (generic function with 1 method)

In [40]:
ps = Persona(:infectado, 20, 0, rand(2), rand(2).-0.5)
p = (ps,)
for i in 1:50
    ps = Persona(:suceptible, 20, 0, rand(2), rand(2).-0.5)
    p = push(ps, p...)
end

Suceptibles, Infectados, Enfermos, Muertos, Recuperados = contar_casos(p...)
println("Suceptibles = $Suceptibles, Infectados = $Infectados, Enfermos  = $Enfermos, 
            Muertos  = $Muertos, Recuperados  = $Recuperados")
simular_contagios(p..., rango_de_contagio = .1,  p_muerte = 0.00001, p_contagiar = .01,)

Suceptibles = 50, Infectados = 1, Enfermos  = 0, 
            Muertos  = 0, Recuperados  = 0
Suceptibles = 50, Infectados = 1, Enfermos  = 0, 
            Muertos  = 0, Recuperados  = 0
Suceptibles = 50, Infectados = 1, Enfermos  = 0, 
            Muertos  = 0, Recuperados  = 0
Suceptibles = 50, Infectados = 1, Enfermos  = 0, 
            Muertos  = 0, Recuperados  = 0
Suceptibles = 50, Infectados = 1, Enfermos  = 0, 
            Muertos  = 0, Recuperados  = 0
Suceptibles = 50, Infectados = 1, Enfermos  = 0, 
            Muertos  = 0, Recuperados  = 0
Suceptibles = 50, Infectados = 1, Enfermos  = 0, 
            Muertos  = 0, Recuperados  = 0
Suceptibles = 50, Infectados = 0, Enfermos  = 1, 
            Muertos  = 0, Recuperados  = 0
Suceptibles = 50, Infectados = 0, Enfermos  = 1, 
            Muertos  = 0, Recuperados  = 0
Suceptibles = 50, Infectados = 0, Enfermos  = 1, 
            Muertos  = 0, Recuperados  = 0
Suceptibles = 50, Infectados = 0, Enfermos  = 1, 
            Muertos 

            Muertos  = 0, Recuperados  = 0
Suceptibles = 50, Infectados = 0, Enfermos  = 1, 
            Muertos  = 0, Recuperados  = 0
Suceptibles = 50, Infectados = 0, Enfermos  = 1, 
            Muertos  = 0, Recuperados  = 0
Suceptibles = 50, Infectados = 0, Enfermos  = 1, 
            Muertos  = 0, Recuperados  = 0
Suceptibles = 50, Infectados = 0, Enfermos  = 1, 
            Muertos  = 0, Recuperados  = 0
Suceptibles = 50, Infectados = 0, Enfermos  = 1, 
            Muertos  = 0, Recuperados  = 0
Suceptibles = 50, Infectados = 0, Enfermos  = 1, 
            Muertos  = 0, Recuperados  = 0
Suceptibles = 50, Infectados = 0, Enfermos  = 1, 
            Muertos  = 0, Recuperados  = 0
Suceptibles = 50, Infectados = 0, Enfermos  = 1, 
            Muertos  = 0, Recuperados  = 0
Suceptibles = 50, Infectados = 0, Enfermos  = 1, 
            Muertos  = 0, Recuperados  = 0
Suceptibles = 50, Infectados = 0, Enfermos  = 1, 
            Muertos  = 0, Recuperados  = 0
Suceptibles = 50, Infectado

### Tipos de argumentos en las funciones

Ya tenemos bastante sobre cómo construir una función, pero aún nos quedan algunos trucos por aprender sobre cómo definir funciones. Lo primero es el tipo de argumentos que hay. Digamos que queremos hacer una función para estimar la altura a la que llega un objeto que lanzamos en tiro parabólico. Para hacer el cálculo necesitamos $\vec{x}_0$, $\vec{v}_0$ y la constante $g$ de la gravitación. 

sabemos que la altura la podemos obtener vía: 

$E = \frac{1}{2}mv^2 + mgh$, cuando $v = 0$ se llega a la máxima altura y $E = \frac{1}{2} m v_{y0}^2 + mgy_0$, de tal forma que $h = \frac{1}{2g} v_{y0}^2 + y_0$. 

La función será: 

h(vy0,y0, g) = (1/(2*g))*vy0+y0

pero sabemos que muy frecuentemente g = 9.81 y y0 = 0. por lo tanto podemos poner esas dos cantidades predefinidas en la función, es decir: 

In [41]:
h(vy0,y0 = 0, g = 9.81, vi = 5) = (1 / (2g))*vy0^2 + y0

h (generic function with 4 methods)

In [42]:
h(10)

5.09683995922528

Noten que la función h ahora tiene 3 métodos, uno es con un solo argument (vy0), otro método es con 2 argumentos (incluyendo y0) y finalmente con 3 argumentos (incluyendo también g). 

Otra posibilidad más, es usar los key-arguments, es decir, argumentos que no dependen de el orden en el que los pongo, pero sí del símbolo que uso para definirlos. Por ejemplo, esta función se podría definir como: 

In [43]:
h(vy0; y0 = 0, g = 9.81) = (1/(2g))vy0^2+y0

h (generic function with 4 methods)

Ahora se ha puesto después del vy0 un ";" en vez de ",". La diferencia es que ahora para cambiar el argumento de y0 o de g, tengo que nombrarlos. 

In [44]:
h(10, g = 1.5)

33.33333333333333

#### Operador ...

el operador ... sirve como en matemáticas, para denotar que los argumentos de una función continuan.

Por ejemplo:

In [45]:
function f(x...)
    length(x)
end

f (generic function with 2 methods)

In [46]:
f(1,3,5,9,10, 11, "a", "33")

8

In [47]:
function f(x...)
    xs = zeros(2)
    for x0 in x[1:2:end]
        xs[1] += x0
    end
    for x0 in x[2:2:end]
        xs[2] += x0
    end
    return xs
end

f (generic function with 2 methods)

In [48]:
a = (1,2,3,4,5,6,4,6,7,8,2,3,5,2,7,4,6)
f(a...)


2-element Vector{Float64}:
 40.0
 35.0

En algunos casos conviene convertir los argumentos en un arreglo. Para esto podemos usar la función collect

In [49]:
function norma(x...)
    xx = collect(x)
    √(x⋅x)
end

norma (generic function with 1 method)

In [50]:
norma(1,2,3,4), √([1,2,3,4]⋅[1,2,3,4])

(5.477225575051661, 5.477225575051661)

### Funciones de funciones y funciones anónimas

Entre los argumentos que puede tener una función están las funciones. Relativamente pronto veremos por ejemplo que podemos definir la función derivada de una función y esta tendrá como argumento otra función. 

Además, en general podemos hacer composición de funciones usando el símbolo ∘ (\circ +Tab). 

In [51]:
f(x) = x^5
(sqrt ∘ f)(3)

15.588457268119896

In [52]:
g_cuadrada(g) = g ∘ g

g_cuadrada (generic function with 1 method)

In [53]:
g_cuadrada(x-> sin(x))(2)

0.7890723435728884

Otra forma práctica de aplicar una función es mediante el símbolo |>. Por ejemplo

In [54]:
3 |> f |> sqrt, sqrt(f(3))

(15.588457268119896, 15.588457268119896)

Esto es práctico cuando se hacen funciones largas que arrgojan algo que se quiere aplicar a otra función. Pronto con la lectura de bases de datos veremos ejemplos. También cuando se quieren aplicar distintas funciones a distintos valores de un arreglo: 

In [55]:
[1,2,3,4] .|> [f, sin, cos, sqrt]

4-element Vector{Real}:
  1
  0.9092974268256817
 -0.9899924966004454
  2.0

Hay veces donde uno no quiere nombrar una función nueva pero requiere ponerla en el argumento de otra función. Entonces se pueden usar funciones anónimas. Estas se definen con ->. Por ejemplo: 

In [56]:
x -> sin(x)

#10 (generic function with 1 method)

In [57]:
g = g_cuadrada(x -> sin(x))

var"#12#13"() ∘ var"#12#13"()

In [58]:
g(1), sin(sin(1))

(0.7456241416655579, 0.7456241416655579)

### Funciones sort, sort! y findall
Ya vimos antes la función sort, pero no le hemos sacado todo el jugo posible al key-argument "by". Analicemos lo que habíamos visto: 

In [59]:
y = [rand(3) for i ∈ 1:100]
sort(y, by = x-> x[2]);

en este caso, dijimos que sort ordenaba utilizando el segundo elemento de cada arreglo. Ahora vemos que sort utiliza un key argument que es de hecho una función anónima que lo que hace es leer el segundo elemento. Es decir, eso es igual que: 

In [60]:
f(x) = x[2]
sort(y, by = f);

sólo que antes estaba escrito en una sola linea, con la función "f" definida en la función anónima. Podemos entonces ordenar los números siguiento reglas tan extrañas como querramos: 

In [61]:
sort!(y, by = x-> -(x[1]-x[2])*abs(x[3]))

100-element Vector{Vector{Float64}}:
 [0.8551113618710033, 0.1425987018294892, 0.9725327930265049]
 [0.9893409335572334, 0.2023675126714839, 0.7979179614295917]
 [0.849442073593353, 0.296450971280769, 0.8665229536651233]
 [0.8584455445552459, 0.05166565185607119, 0.5643668734209093]
 [0.911331337423577, 0.3354213014038012, 0.7757776768706628]
 [0.7852272883032099, 0.05906672399410384, 0.5917572383638612]
 [0.611158516122358, 0.12242489395662437, 0.8527535348138695]
 [0.8799308373066701, 0.387311786940854, 0.8392161689415638]
 [0.9866452105745338, 0.48572885803167076, 0.7542851596080451]
 [0.9458388462244911, 0.5333443446032764, 0.911879369601651]
 [0.5612293972564517, 0.07084217184206776, 0.753159535155522]
 [0.899002837161464, 0.430967651136537, 0.7694979170321674]
 [0.7757866728680227, 0.15205707810288072, 0.5738085989653794]
 ⋮
 [0.2423699165816564, 0.8794792692527942, 0.4225068352134467]
 [0.49279494506806154, 0.9387121786788788, 0.7407893364032898]
 [0.07038388704021248, 0.5541155

In [62]:
y

100-element Vector{Vector{Float64}}:
 [0.8551113618710033, 0.1425987018294892, 0.9725327930265049]
 [0.9893409335572334, 0.2023675126714839, 0.7979179614295917]
 [0.849442073593353, 0.296450971280769, 0.8665229536651233]
 [0.8584455445552459, 0.05166565185607119, 0.5643668734209093]
 [0.911331337423577, 0.3354213014038012, 0.7757776768706628]
 [0.7852272883032099, 0.05906672399410384, 0.5917572383638612]
 [0.611158516122358, 0.12242489395662437, 0.8527535348138695]
 [0.8799308373066701, 0.387311786940854, 0.8392161689415638]
 [0.9866452105745338, 0.48572885803167076, 0.7542851596080451]
 [0.9458388462244911, 0.5333443446032764, 0.911879369601651]
 [0.5612293972564517, 0.07084217184206776, 0.753159535155522]
 [0.899002837161464, 0.430967651136537, 0.7694979170321674]
 [0.7757866728680227, 0.15205707810288072, 0.5738085989653794]
 ⋮
 [0.2423699165816564, 0.8794792692527942, 0.4225068352134467]
 [0.49279494506806154, 0.9387121786788788, 0.7407893364032898]
 [0.07038388704021248, 0.5541155

Otra función muy útil es findall, que encuentra usando una función booleana, todos los valores de un arreglo con los que la función arroja true. Por ejemplo, en este caso se obtienen todos los valores donde la segunda entrada del arreglo es menor que 0.2.

In [63]:
findall(x ->x[2] <= 0.2 , y)

23-element Vector{Int64}:
  1
  4
  6
  7
 11
 13
 15
 17
 18
 24
 26
 28
 29
 31
 33
 34
 35
 39
 43
 46
 53
 56
 60

In [64]:
findall(x-> x[1]< 0.5 && x[2]> 0.9, y)

7-element Vector{Int64}:
  74
  78
  90
  92
  94
  96
 100

In [65]:
y[85]

3-element Vector{Float64}:
 0.41283392850139977
 0.685623493071027
 0.6922225604340131

### Variables globales y locales

Antes de hablar de las variables globales y locales, quisiera hacer notar una curiosidad: 

In [66]:
function f1(x1::Number)
    a1 = 1
    x1 += a1
    return x1
end

f1 (generic function with 1 method)

In [67]:
x = 1

1

In [68]:
f1(x)

2

In [69]:
x

1

In [70]:
a1

LoadError: UndefVarError: a1 not defined

In [71]:
function f2(x2::Number)
    x2 += a2
    return x2
end

f2 (generic function with 1 method)

In [72]:
a2 = 8
x = 1
f2(x)

9

In [73]:
x

1

In [74]:
a3 = 10
function f3(x3::Number)
    a3 += 1
    x3 += a3
    return x3
end

f3 (generic function with 1 method)

In [75]:
x = 1
f3(x)

LoadError: UndefVarError: a3 not defined

In [76]:
function f4(x4::Array)
    a4 = 1
    x4 .+= a4
    return x4
end

f4 (generic function with 1 method)

In [77]:
y = [1,2]

2-element Vector{Int64}:
 1
 2

In [78]:
f4(y)

2-element Vector{Int64}:
 2
 3

In [79]:
y

2-element Vector{Int64}:
 2
 3

In [80]:
a4

LoadError: UndefVarError: a4 not defined

In [81]:
function f5(x5::Array)
    a5 = 1
    x5 = x5 .+ a5
    return x5
end

f5 (generic function with 1 method)

In [82]:
y = [1,2]
f5(y)

2-element Vector{Int64}:
 2
 3

In [83]:
y

2-element Vector{Int64}:
 1
 2

In [84]:
ismutable([1,2]), ismutable(1), ismutable('c'), ismutable("hola")

(true, false, false, true)

Esto es importante porque, si están trabajando con números pueden despreocuparse, las variables no se van a modificar dentro de su función. Sin embargo, si están trabajando con arreglos (y quizá otros tipos de variables, como las cadenas), pueden terminar modificando su variable innintencionalmente de forma global y que el proceso final no resulte bien. Para evitarlo uno puede hacer una copia de su variable. 

In [85]:
x = [1,2]
x_copy = copy(x)

2-element Vector{Int64}:
 1
 2

In [86]:
x_copy .+= 1

2-element Vector{Int64}:
 2
 3

In [87]:
x

2-element Vector{Int64}:
 1
 2

Aquí hay que tener cuidado un cuidado extra. Es un poco complicado cómo son los arreglos en la memoria. Estos consisten de un dato que dice el tamaño del arreglo y un conjunto de apuntadores de memoria sobre qué objetos se tienen. Digamos que se ve algo así: 

a = [#12342, #23212, #133342] -> #1555553

Cada uno de esos números son un apuntador hacia la memoria donde está alojada la información del elemento. Entonces, cuando se hace copy(a), lo que se genera es un arreglo más o menos así: 

copy(a) = [#1555554, #1555555, #1555556] -> #1555557

donde los valores dentro del arreglo son una copia idéntica de los valores en #12342, #23212 y #133342. 

Pero puede suceder que por ejemplo #12342, fuera de hecho un arreglo. Por ejemplo

#12342 = [#112, #113, #114]

entonces, en la copia de a, el valor #1555554, estará en otra posición de la memoria, pero apuntará a los mismos #112, #113 y #114, de forma que al modificar esos elementos, se modifique también el valor de copy(a). 

In [88]:
x = [[1,2], 1]
y = copy(x)


2-element Vector{Any}:
  [1, 2]
 1

In [89]:
x[1][1] = 2

2

In [90]:
x

2-element Vector{Any}:
  [2, 2]
 1

In [91]:
y

2-element Vector{Any}:
  [2, 2]
 1

Entonces, en general está bien usar copy para resolver el problema de que una función actualice el valor de una variable, pero cuando nuestras variables son arreglos de arreglos (o cosas más complicadas), debemos usar deepcopy, que lo que hace es modificar todos los apuntadores. 

In [92]:
x = [[1,2], 1]
y = deepcopy(x)

2-element Vector{Any}:
  [1, 2]
 1

In [93]:
y

2-element Vector{Any}:
  [1, 2]
 1

In [94]:
x[1][1] = 2

2

In [95]:
x

2-element Vector{Any}:
  [2, 2]
 1

In [96]:
y

2-element Vector{Any}:
  [1, 2]
 1

Se tiene que tomar en cuenta que hacer deepcopy es un proceso más lento (y puede ser mucho más lento) que hacer sólo copy, así que vale la pena verificiar si es necesario usar deepcopy. 

También puede pasar que de hecho con la función se quiera modificar el valor de la variable en cuestión. Esto por supuesto sólo se puede hacer si la variable es mutable. En ese caso "despreocúpense de usar copy", pero si lo hacen, por convención, utilicen el símbolo ! al final del nombre de su variable. 

Es parte de las buenas prácticas de programación. Por ejemplo: 

In [97]:
function f6(x6::Array)
    x6 .+= 1
end

f6 (generic function with 1 method)

In [98]:
y = [1,2]
f6(y)

2-element Vector{Int64}:
 2
 3

In [99]:
y

2-element Vector{Int64}:
 2
 3

es una función que modifica el valor de la x, por lo tanto debería de llamarse en realidad f!(x) y no f(x). 

In [100]:
function f6!(x6::Array)
    x6 .+= 1
end

f6! (generic function with 1 method)

Aún no hemos explicado por qué

no genera una variable a = 1. La razón es que para evitar conflictos, siempre que una variable no esté definida extrictamente global en Julia (como las constantes), todas las variables que no están entre los argumentos de la función y que se utilizan para definir la función, son variables locales. 

Las variables en un bloque pueden venir (o no) de un input y pueden modificar (o no) variables fuera del bloque. Cuando una variable se generó dentro de un bloque y no modifica una variable fuera del bloque, decimos que es local. 

Una variable que está dentro de todos los bloques y puede ser modificada en todos los bloques es una variable global. 

Para el resto de los casos se habla del scope, que es el alcance de las variables dentro de un bloque. En lo que explicaré enseguida llamaré notebook a todo lo que no son bloques (de cualquier cosa que se comience con un comando y se termine con "end"). 

- Comenzano por los bloques más sencillos, que son los condicionales y begin. En ambos bloques, las variables tienen el mismo alcanze que en el notebook, es decir, lo que se defina ahí afecta al notebook y lo que se defina en el notebook afecta los bloques formados por if y por begin. 

- Las variables definidas por primera vez dentro de los ciclos for y while son locales, pero las variables que fueron definidas en el notebook, sí son reconocidas en los ciclos y pueden ser modificadas. 

- En las funciones, todas las variables (excepto por los argumentos y las variables globales) son locales. Los argumentos son variables locales si son inmutables y tienen el mismo alcance que en el notebook si son mutables. 

In [101]:
##############
#  notebook  #
##############

a7 = 1
if true
    a7 += 1
    c7 = 1
end

1

In [102]:
a7, c7

(2, 1)

In [103]:
##############
#  notebook  #
##############

a8 = 1
for i in 1:2
    a8 += 1
    c8 = 2
end

In [104]:
a8

3

In [105]:
c8

LoadError: UndefVarError: c8 not defined

In [106]:
##############
#  notebook  #
##############

a9 = 1
function f9(x9)   
    a9 = a9 + 1
    x9 = x9 + a9
    a10 = 1
end

f9 (generic function with 1 method)

In [107]:
x9 = 1
f9(x9)

LoadError: UndefVarError: a9 not defined

In [108]:
##############
#  notebook  #
##############

a10 = 1
function f10(x10)   
    a10 = 4
    x10 += 1
end

f10 (generic function with 1 method)

In [109]:
x10 = 1
f10(x10)

2

In [110]:
x10, a10

(1, 1)

Hasta este punto vimos que las variables en general tienen un scope determinando por el tipo de bloque donde se generaron y se operan. Pero se puede forzar a tener variables que sean locales (que sólo sirvan dentro del bloque) y variables que sean globales (que una vez definidas sean reconocidas en todos lados y sean alteradas en todos lados). Para esto usamos local y global respectivamente: 

In [111]:
function genera_variable_global_absurda()
    global variable_global_absurda = 1
end

genera_variable_global_absurda (generic function with 1 method)

In [112]:
variable_global_absurda

LoadError: UndefVarError: variable_global_absurda not defined

In [113]:
genera_variable_global_absurda()

1

In [114]:
variable_global_absurda 

1

In [115]:
if true 
    local variable_local_absurda = 1
end

1

In [116]:
variable_local_absurda

LoadError: UndefVarError: variable_local_absurda not defined

In [117]:
function utiliza_pi_como_2()
    local π = 2
    π^2
end

utiliza_pi_como_2 (generic function with 1 method)

In [118]:
utiliza_pi_como_2()

4

In [119]:
π

π = 3.1415926535897...

In [120]:
π = 2

LoadError: cannot assign a value to variable MathConstants.π from module Main

Casi siempre las variables globales son constantes. Por ejemplo, pueden definir la constante de Plank y que esta sea una variable global (que sea tratada ya como un número). Para eso se usa const

In [121]:
const hplank = 6.62607015e-34

6.62607015e-34

In [122]:
hplank

6.62607015e-34

In [123]:
function Energía_de_un_fotón(ν)
    hplank*ν
end

Energía_de_un_fotón (generic function with 1 method)

In [124]:
Energía_de_un_fotón(1.2)

7.95128418e-34

In [125]:
hplank = 2

LoadError: invalid redefinition of constant hplank

La ventaja de usar constantes son 2: 
1. No es posible re-definir la constante por error en el código. 
2. Es más rápida la operación con constantes que por variables! 

### Modificar funciones pre-definidas (para agregar métodos). 

Lo último que veremos en este video-notebook, es como modificar una función predefinida. 

In [126]:
import Base.+, Base.*

In [136]:
function +(personas::Persona...)
    Diccionario = Dict([(:suceptible,1),(:infectado,2),(:enfermo,3),(:muerto,4),(:recuperado,5)])
    Diccionario_de_regreso = [:suceptible,:infectado,:enfermo,:muerto,:recuperado]
    estado_de_salud = 0#Diccionario(personas[1].estado_de_salud)
    edad = 0#personas[1].edad
    tiempo_salud = 0#personas[1].tiempo_salud
    posicion = zeros(length(personas[1].posicion))#personas[1].posicion
    velocidad = zeros(length(personas[1].posicion))#personas[1].velocidad
    for p ∈ personas
         estado_de_salud += Diccionario[p.estado_de_salud]
         edad += p.edad
         tiempo_salud += p.tiempo_salud
         posicion .+= p.posicion
         velocidad .+= p.velocidad
    end
    estado_de_salud = min(5, ceil(Int, estado_de_salud/length(personas)))
    p = Persona(Diccionario_de_regreso[estado_de_salud], round(Int, edad/length(personas)), 
        tiempo_salud/length(personas), posicion./length(personas), velocidad./length(personas))
end 

function *(persona::Persona, a::Number)
    estado_de_salud = persona.estado_de_salud
    edad = persona.edad*a
    tiempo_salud = persona.tiempo_salud*a
    posicion = persona.posicion.*a
    velocidad = persona.velocidad.*a
    p = Persona(estado_de_salud, edad, tiempo_salud, posicion, velocidad)
end 

* (generic function with 329 methods)

In [137]:
ps = Persona(:infectado, 20, 0, rand(2), rand(2).-0.5)
p = (ps,)
for i in 1:50
    ps = Persona(rand([:infectado, :suceptible]), rand(1:100), 0, rand(2), rand(2).-0.5)
    p = push(ps, p...)
end

In [138]:
p[1] + p[2] + p[3]

Persona(:infectado, 45, 0.0, [0.356164599834292, 0.5882780922240146], [-0.002588798798029831, 0.016918643062994176])

In [139]:
+(p...)

Persona(:infectado, 54, 0.0, [0.5930421819807661, 0.558422573588657], [-0.022383870189282482, -0.006747273172231282])

In [140]:
p[1] + p[2]

Persona(:infectado, 60, 0.0, [0.12249820748173423, 0.5278501709887294], [0.22958197881032205, 0.08244126794082862])