# Operaciones básicas

### Operaciones con números

En Julia existen predefinidas un **titipuchal** de operaciones básicas que se pueden usar (como si se tratara de una calculadora). 

Ya notaron que por ejemplo están las operaciones como la suma o la multiplicación, que se expresan con " + " y con " * " respectivamente. 

También están por supuesto definidas la resta " - ", la divición " / " y la potencia " ^ ". 

**Intenta hacer algunas operaciones entre números utilizando estos símbolos.** 

Estas operaciones les voy a llamar operadores. Los operadores en Julia son funciones en realidad. Por ejemplo, la suma entre dos números, se puede escribir como +(a,b), lo que significa a + b. 

In [1]:
+(1,1)

2

In [2]:
+(1,2,3)

6

In [3]:
/(1,2)

0.5

In [4]:
^(2,8)

256

Esto es algo importante de Julia, todo son en realidad funciones. Exceptuando estos operadores (y unos pocos más), en general en Julia se escriben las funciones como " Nombre_de_la_funcion(argumentos) ". 

Por ejemplo, la función seno de x se escribe como sin(x), donde x es un valor numérico. 

Como ya dije, hay un titipuchal de funciones pre-cargadas. Esto incluye todas las trigonométricas, la exponencial, logaritmo, etc. En general los nombres de las funciones están en inglés y son relativamente intuitivos. Por ejemplo, de tangente es tan(x), de tangente hiperbólica es tanh(x), etc. Uno puede intentar simplemente adivinar el nombre de la función y si no está seguro de cómo se escribe, presiona tab con las primeras letras y aparecerán las opciones. Otra opción es buscar dentro de la documentación de Julia aquí: https://docs.julialang.org/en/v1/

**Intenta** por ejemplo encontrar la función que calcula el mínimo común múltiplo (least common multiple) entre dos números:

**Intenta** buscar la función piso (el mayor entero menor que x) en Julia y aplícala a 15.3 y a -15.3. 

**Intenta** buscar la función módulo n de un número. Explora qué es lo que hace esta función, nos va a ser útil para aplicar condiciones periódicas a la frontera (por ejemplo para simular cristales). 

Por supuesto, no podemos ver todas las funciones pre-definidas aquí, porque son realmente muchas. A veces, adivinarán el nombre de la función completando con Tab, pero no lograrán usarla. Para preguntar en el notebook cómo se usa sin tener que buscar en la documentación, pueden utilizar el símbolo " ? " antes del nombre de la función. Por ejemplo:

**Si tienes interés en alguna función en particular** trata de adivinar cómo se llama en Julia (no están todas, pero sí muchas) y pregunta qué hace. 

**Una función que usaremos mucho es tan(x,y)** pregunta al notebook la información sobre *tan*, dentro busca qué hace cuando se agregan dos argumentos. 

### Operaciones con cadenas

Además de las operaciones entre números (que hay de varios tipos, como veremos en el siguiente video), hay operaciones con cadenas de caracteres. 

Estas operaciones pueden ser muy útiles para generar nombres de archivos correctamente. 

In [5]:
a = "Hola "
b = "Ata"
c = 'c'
a*b

"Hola Ata"

Una función muy importante con las cadenas es obtener un número a partir de una cadena que representa un número. Por ejemplo la cadena "12.5" representa el número $12.5$. Para transformar una cadena en un número se utiliza la función parse. 

In [6]:
parse(Float64, "45")

45.0

**Transforma** la cadena "1.5434" en su correspondiente número.  

También puede ser que quieras agregar algún dato a una cadena. Por ejemplo, obtienes el valor de una función y quieres escribir ese valor. Eso se llama interpolación y se hace utilizando el signo $ de la siguiente manera: 

In [7]:
sin_de_pi_sobre_3 = "sin(\u03C0/3)+2 = $(sin(π/3)+2)"

"sin(π/3)+2 = 2.8660254037844384"

In [8]:
println(sin_de_pi_sobre_3)
println("está way!")

sin(π/3)+2 = 2.8660254037844384
está way!


Aquí además agregué como un caracter $\pi$, que no es fácil de escribir con un teclado típico, para esto utilicé Unicode. Para agregar un caracter utilizando Unicode, se pone \u y el número de Unicode. Para obtener el Unicode de un caracter pueden utilizar la función Char de la siguiente forma:  

In [9]:
Char('π')

'π': Unicode U+03C0 (category Ll: Letter, lowercase)

La parte importante es lo que viene después del U+. 

**Obtén el Unicode** de $\forall$ y de $\exists$, para escribir la cadena: "$\forall \quad x \quad \exists \quad  y > x$"

Una última función útil con las cadenas, es la función lenght, que arroja el tamaño de la cadena: 

In [10]:
length("Hola, ¿cómo estás?")

18

Hay varias operaciones más que se pueden aplicar sobre cadenas (y caracteres), pero para aplicar algunas de ellas necesitamos explicar un poco sobre funciones antes, así que volveremos más adelante. 

Pero antes de terminar esta sección, quisiera decir que para acceder a un caracter de una cadena, se pueden usar corchetes: 

In [11]:
nombre = "Fulanita"
saludo = "Hola $nombre"

"Hola Fulanita"

In [12]:
saludo[3]

'l': ASCII/Unicode U+006C (category Ll: Letter, lowercase)

Y de hecho, se puede acceden a un conjunto de los caracteres (formando una cadena), poniendo un *arreglo* o un *rango* dentro de los corchetes:

In [13]:
saludo[1:8]

"Hola Ful"

In [14]:
saludo[[1,3,5,7,9]]

"Hl ua"

### Operaciones booleanas

y también existen operaciones booleanas, es decir, que lo que arrojan es true o false. Aquí por ejemplo está el operador ==, que no es lo mismo que =.  

= sirve para definir algo, como asignar el valor "Hola " a la variable a. == es un operador que compara dos variables, por lo tanto se puede escribir como ==(a,b) o como a == b 

In [15]:
b

"Ata"

In [16]:
"Ata" == b

true

In [17]:
==("Ata",b)

true

In [18]:
1 == 2

false

otros operadores importantes son !=, !, <, <=, >, >= 

**Has diferentes pruebas** con esos operadores, descubre cómo funcionan y cuándo arrojan resultados inesperados. Nósolo compares números, compara también cadenas, por ejemplo. ¿Qué significa < con cadenas?

Hay un operador un poco extraño, ===. Éste busca comparar si dos valores son idénticos en un sentido computacional, es decir, si la forma en la que se almacenan en la memoria es la misma.

In [19]:
1 === 1.

false

In [20]:
1 == 1.

true

En ese caso 1 y 1. son iguales en valor, pero no sin idénticos, porque en un caso se trata de un entero, en el otro de un flotante. 

También está el operador ≈ que revisa si dos números son aproximadamente iguales. 

In [21]:
0.1 ≈ 0.1 + 1e-9

true

In [22]:
0.1 ≈ 0.11

false

In [23]:
BigFloat("0.1") ≈ BigFloat("0.1") + 1e-40

true

Finalmente, están los operadores &&, || y ⊻, que son el equivalente a "y", "o" y "o" exclusivo. 

In [24]:
(1 == 1) && (1 == 2)

false

In [25]:
(1 == 1) || (1 == 2)

true

In [26]:
(1 == 1) ⊻ (1 == 1)

false

In [27]:
(1 == 1) ⊻ (1 == 2)

true

También hay funciones que están definidas sobre los booleanos, por ejemplo la suma entre booleanos y el producto entre booleanos y entre números y booleanos. Esto significa que por ejemplo todas las funciones que se definen con un desarrollo de Taylor están definidas, aunque no tengan un significado interesante: 

In [28]:
exp(true) 

2.718281828459045

In [29]:
sin(false)

0.0

### Operaciones con arreglos

Además de los números, las cadenas y los booleanos, utilizaremos con mucha frecuencia los arreglos. 

Un arreglo es una lista de "objetos", esos objetos pueden ser números, cadenas, otros arreglos u otros objetos extraños. Para iniciar un arreglo se utiliza el símbolo [ y para terminar dicho arreglo se utiliza el símbolo ]. Dentro los elementos se separan utilizando comas: 

In [30]:
v = [1,2,3]

3-element Vector{Int64}:
 1
 2
 3

In [31]:
a = 2*v

3-element Vector{Int64}:
 2
 4
 6

In [32]:
b = ["hola", 1, [1,[1.2,2]]]

3-element Vector{Any}:
  "hola"
 1
  Any[1, [1.2, 2.0]]

Para acceder a los elementos de un arreglo, se escribe el nombre del arreglo, seguido por [n], donde n corresponde al número de elemento: 

In [33]:
a[2]

4

In [34]:
b[[1,3]]

2-element Vector{Any}:
 "hola"
 Any[1, [1.2, 2.0]]

In [35]:
b[3][2][1]

1.2

En este último ejemplo el tercer elemento de b es también un arreglo, así que puedo acceder a sus elementos nuevamente utilizando corchetes. 

In [36]:
b[3][1]

1

Las cadenas de caracteres también son en realidad arreglos, así que puedo acceder a cada caracter con corchetes. 

In [37]:
b[1][3]

'l': ASCII/Unicode U+006C (category Ll: Letter, lowercase)

In [38]:
"hola fulanito"[6]

'f': ASCII/Unicode U+0066 (category Ll: Letter, lowercase)

**¿Cuál es el elemento a[1][2][3] si a = [[1, [2, [3]], 2], ["hola", "adios"]]?**

Para aplicar una función que no está definida para arreglos (matrices) a todos los elementos de un arreglo (matriz), se tiene que agregar un "." antes del paréntesis de la función, por ejemplo: 

In [39]:
cos.(a)

3-element Vector{Float64}:
 -0.4161468365471424
 -0.6536436208636119
  0.960170286650366

**Aplica la función exponencial a la lista de valores [1,2,3,4]**

En el caso de los operadores, también se puede usar el truco del ".", pero en este caso el punto va antes del operador. Por ejemplo:

In [40]:
a .+ a, a .^2

([4, 8, 12], [4, 16, 36])

In [41]:
a .+ 1

3-element Vector{Int64}:
 3
 5
 7

Otra operación importante en los arreglos es conocer el tamaño que tienen, para esto se usa length. 

In [42]:
length([1,2,3,4.66])

4

También suele ser importante el poder ordenar un arreglo. Para esto usamos sort: 

In [43]:
x = rand(100)

100-element Vector{Float64}:
 0.46226609226399407
 0.7625009471209063
 0.32620572897723443
 0.46367429539388594
 0.5841702588045559
 0.7478689005092856
 0.16075068672731363
 0.38460011582609455
 0.9425126498620937
 0.62911806733594
 0.8410183307087515
 0.37943554630752807
 0.23946390410607532
 ⋮
 0.8630894420236292
 0.5031701677212113
 0.9073244917231953
 0.1033471941637012
 0.4221893801224874
 0.12119200657494855
 0.2536509587564313
 0.2022790536619068
 0.36648303316473174
 0.7727655969251617
 0.9202544961602244
 0.8126624907523372

In [44]:
sort(x)

100-element Vector{Float64}:
 0.0009262077623004572
 0.0034182062585992323
 0.021535711939730584
 0.025330985384756977
 0.02928830731661014
 0.0430065063044105
 0.053020044105581254
 0.08463983925572904
 0.1033471941637012
 0.10535936655521083
 0.10717168833686097
 0.1083792747100969
 0.11520618339837396
 ⋮
 0.9158621080120861
 0.9202544961602244
 0.9317125757424976
 0.9373191269082286
 0.9397399875077408
 0.9425126498620937
 0.9644054933475137
 0.9648434139304665
 0.9667031035405282
 0.9678678367437814
 0.9796663571816528
 0.9877082998294502

Si queremos ordenar de forma inversa podemos usar: 

In [45]:
sort(x, rev = true)

100-element Vector{Float64}:
 0.9877082998294502
 0.9796663571816528
 0.9678678367437814
 0.9667031035405282
 0.9648434139304665
 0.9644054933475137
 0.9425126498620937
 0.9397399875077408
 0.9373191269082286
 0.9317125757424976
 0.9202544961602244
 0.9158621080120861
 0.9073244917231953
 ⋮
 0.1083792747100969
 0.10717168833686097
 0.10535936655521083
 0.1033471941637012
 0.08463983925572904
 0.053020044105581254
 0.0430065063044105
 0.02928830731661014
 0.025330985384756977
 0.021535711939730584
 0.0034182062585992323
 0.0009262077623004572

también puede ser que tengamos una lista de listas y querramos ordenar utilizando el segundo elemento de la lista, para esto usamos: 

In [46]:
y = [rand(3), rand(3), rand(3), rand(3), rand(3)]

5-element Vector{Vector{Float64}}:
 [0.9248972836206093, 0.835740359035396, 0.9338267499897202]
 [0.0655483069360312, 0.14458148432720797, 0.7137178309820973]
 [0.4665185472305884, 0.5642038963886369, 0.7462951385485226]
 [0.7085082318677627, 0.8577282609757346, 0.3195312548152509]
 [0.14661394170318465, 0.422845763842149, 0.19004216143077923]

In [47]:
sort(y, by = x-> x[2])

5-element Vector{Vector{Float64}}:
 [0.0655483069360312, 0.14458148432720797, 0.7137178309820973]
 [0.14661394170318465, 0.422845763842149, 0.19004216143077923]
 [0.4665185472305884, 0.5642038963886369, 0.7462951385485226]
 [0.9248972836206093, 0.835740359035396, 0.9338267499897202]
 [0.7085082318677627, 0.8577282609757346, 0.3195312548152509]

cómo funciona el argumento by, lo veremos más adelante, pero se puede modificar para utilizar cualquier clase de ordenamiento. No lo explico ahora, porque necesitamos entender cómo hacer una función antes y los tipos de funciones. 

Otras funciones muy importantes sobre los arreglos son: push!, insert!, pop! y deleteat!, append!, ∪ y ∩

In [48]:
x = [1.,2,3,4,5,6]

6-element Vector{Float64}:
 1.0
 2.0
 3.0
 4.0
 5.0
 6.0

In [49]:
push!(x, 6)

7-element Vector{Float64}:
 1.0
 2.0
 3.0
 4.0
 5.0
 6.0
 6.0

In [50]:
x

7-element Vector{Float64}:
 1.0
 2.0
 3.0
 4.0
 5.0
 6.0
 6.0

In [51]:
pop!(x)
x

6-element Vector{Float64}:
 1.0
 2.0
 3.0
 4.0
 5.0
 6.0

In [52]:
insert!(x, 4, 3.2)

7-element Vector{Float64}:
 1.0
 2.0
 3.0
 3.2
 4.0
 5.0
 6.0

In [53]:
deleteat!(x, 4)

6-element Vector{Float64}:
 1.0
 2.0
 3.0
 4.0
 5.0
 6.0

In [54]:
append!(x, [7,6,5,4,3,2,1])

13-element Vector{Float64}:
 1.0
 2.0
 3.0
 4.0
 5.0
 6.0
 7.0
 6.0
 5.0
 4.0
 3.0
 2.0
 1.0

In [55]:
unique!(x)
x

7-element Vector{Float64}:
 1.0
 2.0
 3.0
 4.0
 5.0
 6.0
 7.0

In [56]:
x ∪ [1,2,3,4,100]

8-element Vector{Float64}:
   1.0
   2.0
   3.0
   4.0
   5.0
   6.0
   7.0
 100.0

In [57]:
x ∩ [1,2,100]

2-element Vector{Float64}:
 1.0
 2.0

Finalmente, hay todas las operaciones de álgebra lineal entre matrices o entre vectores. Para estas operaciones, necesitamos cargar la paquetería LinearAlgebra, que está pre-instalada, pero no pre-cargada. 

In [58]:
using LinearAlgebra

Una de las importantes es la norma de un vector:

In [59]:
norm([1,2,3])

3.7416573867739413

También ahí están definidas las operciones de producto punto y producto cruz. 

In [60]:
x ⋅ x, dot(x, x)

(140.0, 140.0)

In [61]:
x = rand(3)

x × (ones(3)), cross(x,ones(3))

([0.08099456252756476, -0.38474156153882344, 0.3037469990112587], [0.08099456252756476, -0.38474156153882344, 0.3037469990112587])

hay un realmente muchas operaciones más definidas en la paquetería de LinearAlgebra

### Matrices

Una matriz es algo parecido a un arreglo (de arreglos), así que para definir una matriz se usan también los corchetes, pero para no generar confusión, los elementos de cada renglón de la matriz se separan con espacios, mientras que los cambios entre renglón y renglón se definen con ;

In [62]:
A = [1 2; 3 4]

2×2 Matrix{Int64}:
 1  2
 3  4

Para no confundirse de qué es lo que uno está escribiendo en una matriz a veces conviene escribirlo visualmente claro: 

In [63]:
A = [1 2 3;
     4 5 6;
     7 8 9]

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

Las matrices también pueden tener casi cualquier cosa como objeto dentro: 

In [64]:
B = [1 "hola";
"saludos" 1//2]

2×2 Matrix{Any}:
 1             "hola"
  "saludos"  1//2

In [65]:
C = [A A;
     A A]

6×6 Matrix{Int64}:
 1  2  3  1  2  3
 4  5  6  4  5  6
 7  8  9  7  8  9
 1  2  3  1  2  3
 4  5  6  4  5  6
 7  8  9  7  8  9

Pero notemos que cuando agregamos una matriz (o un arreglo) como elemento, no lo pone tal cual como un elemento, sino que intenta generar una matriz más grande (como se vio en C, no generó una matriz de $2\times 2$, sino una de $6\times 6$. Para forzar a que los elementos sean matrices (o listas), se tiene que agregar un corchete extra. 

In [66]:
C = [[A] [A]; [A] [A]]

2×2 Matrix{Matrix{Int64}}:
 [1 2 3; 4 5 6; 7 8 9]  [1 2 3; 4 5 6; 7 8 9]
 [1 2 3; 4 5 6; 7 8 9]  [1 2 3; 4 5 6; 7 8 9]

El operador + y * está definido para matrices como la suma entre matrices (entrada por entrada) y el producto matricial, además de que * también está definido entre un número y una matriz como el producto de cada entrada de la matriz por el número. 

Con estas dos definiciones, automáticamente todas las funciones que usan productos y sumas están definidos. Por ejemplo, la potencia está definia. 

In [67]:
C + C

2×2 Matrix{Matrix{Int64}}:
 [2 4 6; 8 10 12; 14 16 18]  [2 4 6; 8 10 12; 14 16 18]
 [2 4 6; 8 10 12; 14 16 18]  [2 4 6; 8 10 12; 14 16 18]

In [68]:
A = ones(3,3)
B = [1 2 3; 4 5 6; 7 8 9]
A*B

3×3 Matrix{Float64}:
 12.0  15.0  18.0
 12.0  15.0  18.0
 12.0  15.0  18.0

In [69]:
3*A

3×3 Matrix{Float64}:
 3.0  3.0  3.0
 3.0  3.0  3.0
 3.0  3.0  3.0

In [70]:
B^5

3×3 Matrix{Int64}:
 121824  149688  177552
 275886  338985  402084
 429948  528282  626616

In [71]:
sin(C)

LoadError: MethodError: no method matching sin(::Matrix{Matrix{Int64}})
Closest candidates are:
  sin(::Float16) at math.jl:1159
  sin(::ComplexF16) at math.jl:1160
  sin(::Complex{T}) where T at complex.jl:831
  ...

Nótese que el sin(C) no es lo mismo que aplicar la función sin a cada una de las entradas de C, sino hacer el desarrollo de Taylor de sin y aplicar las potencias de matrices correspondientes con sus productos y sumas. 

Para aplicar la función sin a cada una de las entradas, podemos usar el mismo truco que para los arreglos, es decir, poner un punto antes del paréntesis: 

In [72]:
sin.(C)

2×2 Matrix{Matrix{Float64}}:
 [-0.692791 -0.23059 0.231611; -0.172432 -0.143353 -0.114274; 0.347927 -0.0561161 -0.460159]  …  [-0.692791 -0.23059 0.231611; -0.172432 -0.143353 -0.114274; 0.347927 -0.0561161 -0.460159]
 [-0.692791 -0.23059 0.231611; -0.172432 -0.143353 -0.114274; 0.347927 -0.0561161 -0.460159]     [-0.692791 -0.23059 0.231611; -0.172432 -0.143353 -0.114274; 0.347927 -0.0561161 -0.460159]

In [73]:
C .^5

2×2 Matrix{Matrix{Int64}}:
 [121824 149688 177552; 275886 338985 402084; 429948 528282 626616]  …  [121824 149688 177552; 275886 338985 402084; 429948 528282 626616]
 [121824 149688 177552; 275886 338985 402084; 429948 528282 626616]     [121824 149688 177552; 275886 338985 402084; 429948 528282 626616]

El equivalente a lenght para matrices, es la función size. lenght también está definido, pero sólo arroja el número de elementos totales de la matriz y no las dimensiones. 

In [74]:
size(C), length(C)

((2, 2), 4)

También hay varias operaciones en la paquetería de AlgebraLineal que nos importan, por ejemplo inverso de una matriz: 

In [75]:
A = [1 1. 1; 2 1 2; 3 3 1]

3×3 Matrix{Float64}:
 1.0  1.0  1.0
 2.0  1.0  2.0
 3.0  3.0  1.0

In [76]:
inv(A)

3×3 Matrix{Float64}:
 -2.5   1.0   0.5
  2.0  -1.0   0.0
  1.5   0.0  -0.5

In [77]:
A^(-1)

3×3 Matrix{Float64}:
 -2.5   1.0   0.5
  2.0  -1.0   0.0
  1.5   0.0  -0.5

Como pueden ver hay dos formas de escribir el inverso de una matriz. A mi me gusta más usar la segunda versión.

Otras importantes son: 

In [78]:
transpose(A) #transpuesta de A

3×3 transpose(::Matrix{Float64}) with eltype Float64:
 1.0  2.0  3.0
 1.0  1.0  3.0
 1.0  2.0  1.0

In [79]:
tr(A) # traza de A

3.0

In [80]:
det(A) # determinante de una matriz

2.0

In [81]:
eigvals(A) # eigenvalores de una matriz

3-element Vector{Float64}:
 -1.483611620543907
 -0.28282386330879794
  4.766435483852703

In [82]:
eigvecs(A) # y sus eigenvectores

3×3 Matrix{Float64}:
 -0.0940992  -0.732014  -0.349239
 -0.57735     0.57735   -0.57735
  0.811056    0.361694  -0.738037

In [83]:
svd(A) #single value decomposition de A

SVD{Float64, Float64, Matrix{Float64}}
U factor:
3×3 Matrix{Float64}:
 -0.314604  -0.196116   0.928743
 -0.517945  -0.784465  -0.341099
 -0.795461   0.588348  -0.145218
singular values:
3-element Vector{Float64}:
 5.378742389226484
 1.414213562373095
 0.262926435221315
Vt factor:
3×3 Matrix{Float64}:
 -0.694749  -0.598454  -0.398969
 -0.0        0.5547    -0.83205
 -0.719252   0.578066   0.385377

Y hay muchas más, la adjunta, transpuesta conjugada, etc...

Vale la pena hacer notar que se puede acceder a los renglones o columnas de una matriz de la siguiente forma: 

In [84]:
C[2,:] #renglones
A[:,2] #columnas

3-element Vector{Float64}:
 1.0
 1.0
 3.0

### Rangos

Los rangos son para casi todo propósito como arreglos. Para escribir el rango de valores de todos los enteros entre 0 y 10 escribimos: 

In [85]:
0:10

0:10

si queremos aplicar a todos estos números una función, lo podemos hacer como con los arreglos. Por ejemplo: 

In [86]:
(0:10).^2

11-element Vector{Int64}:
   0
   1
   4
   9
  16
  25
  36
  49
  64
  81
 100

In [87]:
sin.(0:10)

11-element Vector{Float64}:
  0.0
  0.8414709848078965
  0.9092974268256817
  0.1411200080598672
 -0.7568024953079282
 -0.9589242746631385
 -0.27941549819892586
  0.6569865987187891
  0.9893582466233818
  0.4121184852417566
 -0.5440211108893698

Si queremos un rango que no separe los números inicial y final de 1 en uno, sino de 0.1 en 0.1, lo escribimos así: 

In [88]:
sqrt.((0:3:10).^2)

4-element Vector{Float64}:
 0.0
 3.0
 6.0
 9.0

Nuevamente, ese rango lo podemos tratar como un arreglo para casi todo. 

### Arreglos y matrices a partir de rangos. 

En Julia existe una notación compacta para generar arreglos y matrices que se parece un poco a la notación de conjuntos: 

In [89]:
f(x) = x^2 + 1 
A = 1:10
[f(x) for x ∈ A] 

10-element Vector{Int64}:
   2
   5
  10
  17
  26
  37
  50
  65
  82
 101

In [90]:
f(x,y) = x^2 + y
A = 1:10
B = 1:0.1:10
[f(x,y) for x ∈ A, y ∈ B]

10×91 Matrix{Float64}:
   2.0    2.1    2.2    2.3    2.4  …   10.6   10.7   10.8   10.9   11.0
   5.0    5.1    5.2    5.3    5.4      13.6   13.7   13.8   13.9   14.0
  10.0   10.1   10.2   10.3   10.4      18.6   18.7   18.8   18.9   19.0
  17.0   17.1   17.2   17.3   17.4      25.6   25.7   25.8   25.9   26.0
  26.0   26.1   26.2   26.3   26.4      34.6   34.7   34.8   34.9   35.0
  37.0   37.1   37.2   37.3   37.4  …   45.6   45.7   45.8   45.9   46.0
  50.0   50.1   50.2   50.3   50.4      58.6   58.7   58.8   58.9   59.0
  65.0   65.1   65.2   65.3   65.4      73.6   73.7   73.8   73.9   74.0
  82.0   82.1   82.2   82.3   82.4      90.6   90.7   90.8   90.9   91.0
 101.0  101.1  101.2  101.3  101.4     109.6  109.7  109.8  109.9  110.0

también se pueden hacer unión o intersección de conjuntos: 

In [91]:
[f(x) for x ∈ A] ∪ A

17-element Vector{Int64}:
   2
   5
  10
  17
  26
  37
  50
  65
  82
 101
   1
   3
   4
   6
   7
   8
   9

In [92]:
[f(x) for x ∈ A] ∩ A

3-element Vector{Int64}:
  2
  5
 10

Nótese que en la unión de rangos debe ser claro qué es lo que se quiere unir, sino se genera un error, porque no hay unión entre números. 

In [93]:
0:2:99 ∪ 1:2:99

LoadError: MethodError: no method matching (::Colon)(::Int64, ::Int64, ::Vector{Int64})
Closest candidates are:
  (::Colon)(::T, ::T) where T<:Real at range.jl:5
  (::Colon)(::Real, ::Real) at range.jl:3
  (::Colon)(::T, ::T, ::T) where T<:Real at range.jl:22
  ...

In [94]:
(0:2:99) ∪ (1:2:99)

100-element Vector{Int64}:
  0
  2
  4
  6
  8
 10
 12
 14
 16
 18
 20
 22
 24
  ⋮
 77
 79
 81
 83
 85
 87
 89
 91
 93
 95
 97
 99

In [95]:
(0:2:99) ∩ (1:2:99) #aquí podemos ver alguna diferencia entre rangos y arreglos. 

0:2:-1

In [96]:
[i for i ∈ 0:2:99] ∩ [i for i ∈ 1:2:99]

Int64[]

**Reto: Haz un arreglo que contenga 1000 elementos, de tal forma que el elemento i es 0 si i no es primo y 1 si lo es. Con ese arreglo obtén cuántos primos hay entre los primeros 1000 números.** Hint: necesitas hacer primero una matriz usando la función floor y después usando esa matriz, obtener el arreglo que se pide usando la función sum. 

### El primero en resolver este reto correctamente tiene 2 puntos extra sobre su primera tarea. 